// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckwydnwfzmdzxhhdfrzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrd3lkbndmem1kenhoaGRmcnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzc5NDAsImV4cCI6MjA2NzkxMzk0MH0.JWWdmPQSXeDHIo3Dl19T5NmHTR2kzNiJ5RiG5i_Gwts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});